import type { Project } from "./types";

export const projectTracker: Project = {
    slug: "project-tracker",
    title: "ProjectTracker",
    year: "Apr 2026 — May 2026",
    role: "Product Improvement, UX/UI Redesign",
    summary:
        "UX/UI Redesign and Accessibility Improvements for an AI-Generated Project Management Platform.",
    introVisuals: [
        {
            src: "/ProjectTracker/01_visual01.webp",
            alt: "ProjectTracker project overview visual 1",
        },
        {
            src: "/ProjectTracker/02_visual02.webp",
            alt: "ProjectTracker project overview visual 2",
        },
        {
            src: "/ProjectTracker/03_visual03.webp",
            alt: "ProjectTracker project overview visual 3",
        },
        {
            src: "/ProjectTracker/04_visual04.webp",
            alt: "ProjectTracker project overview visual 4",
        },
    ],
    overview: [
        "**ProjectTracker is a project management platform created to help project managers and teams track projects, deliverables, activities, and timelines in one place.**",
        "The initial version of the ProjectTracker had already been created, especially UI/UX was generated by an AI design program. But the interface needed further refinement to better align with the company’s style guide and usability standards. My responsibility was to audit the existing platform, identify UX/UI issues, and redesign the interface and flow with a stronger focus on UI consistency, information hierarchy and accessibility.",
        "This project focused on improving an existing AI-generated user interface and transforming it into a polished, cohesive, and user-friendly project management application.",
    ],
    caseStudySections: {
        "existing-product": [
            "The initial version of ProjectTracker was created by an AI design program as a project management platform for organizing projects, deliverables, and activities. The product was very functional and covered the core workflows, but further refinement was needed to better align with consistency and colour contrast standards. Also, the company's style guide and usability standards were not followed consistently.",
            "The screens have been recreated while **all colours, button styles and layout are kept exactly the same** with placeholder content to protect confidential company information.",
            { vspace: true },
            {
                screenGallery: {
                    screens: [
                        {
                            label: "Dashboard",
                            src: "/ProjectTracker/05_existing_dashboard.png",
                            alt: "ProjectTracker existing product — Dashboard screen",
                        },
                        {
                            label: "Projects",
                            src: "/ProjectTracker/06_existing_projects.png",
                            alt: "ProjectTracker existing product — Projects screen",
                        },
                        {
                            label: "Deliverable Tracker",
                            navLines: ["Deliverable", "Tracker"],
                            src: "/ProjectTracker/07_existing_deliverable-tracker.png",
                            alt: "ProjectTracker existing product — Deliverable Tracker screen",
                        },
                        {
                            label: "Activity Tracker",
                            navLines: ["Activity", "Tracker"],
                            src: "/ProjectTracker/08_existing_activity-tracker.png",
                            alt: "ProjectTracker existing product — Activity Tracker screen",
                        },
                        {
                            label: "Gantt",
                            src: "/ProjectTracker/09_existing_gantt.png",
                            alt: "ProjectTracker existing product — Gantt screen",
                        },
                        {
                            label: "Mobilization",
                            src: "/ProjectTracker/10_existing_mobilization.png",
                            alt: "ProjectTracker existing product — Mobilization screen",
                        },
                        {
                            label: "Resources",
                            src: "/ProjectTracker/11_existing_resources.png",
                            alt: "ProjectTracker existing product — Resources screen",
                        },
                        {
                            label: "Resource Calendar",
                            src: "/ProjectTracker/12_existing_resource-calendar.png",
                            alt: "ProjectTracker existing product — Resource Calendar screen",
                        },
                    ],
                },
            },
        ],
        audit: [
            "After reviewing the existing product,I identified several UX/UI issues and accessibility concerns that needed to be addressed. I conducted a thorough audit of the product to understand the current state and identify areas for improvement.",
        ],
    },

    tags: ["Product Optimization", "UX/UI Redesign"],
};
