import type { Project } from "./types";

export const projectTracker: Project = {
    slug: "project-tracker",
    title: "ProjectTracker",
    year: "Apr 2026 — May 2026",
    role: "Product Improvement, UX/UI Redesign",
    summary:
        "UX/UI Redesign and Accessibility Improvements for an AI-Generated Project Management Platform.",
    introVisuals: [
        {
            src: "/ProjectTracker/01_visual01.webp",
            alt: "ProjectTracker project overview visual 1",
        },
        {
            src: "/ProjectTracker/02_visual02.webp",
            alt: "ProjectTracker project overview visual 2",
        },
        {
            src: "/ProjectTracker/03_visual03.webp",
            alt: "ProjectTracker project overview visual 3",
        },
        {
            src: "/ProjectTracker/04_visual04.webp",
            alt: "ProjectTracker project overview visual 4",
        },
    ],
    overview: [
        "**ProjectTracker is a project management platform created to help project managers and teams track projects, deliverables, activities, and timelines in one place.**",
        "The initial version of the ProjectTracker had already been created, especially UI/UX was generated by an AI design program. But the interface needed further refinement to better align with the company’s style guide and usability standards. My responsibility was to audit the existing platform, identify UX/UI issues, and redesign the interface and flow with a stronger focus on UI consistency, information hierarchy and accessibility.",
        "This project focused on improving an existing AI-generated user interface and transforming it into a polished, cohesive, and user-friendly project management application.",
    ],
    caseStudySections: {
        "existing-product": [
            "The initial version of ProjectTracker was created by an AI design program as a project management platform for organizing projects, deliverables, and activities. The product was very functional and covered the core workflows, but further refinement was needed to better align with consistency and colour contrast standards. Also, the company's style guide and usability standards were not followed consistently.",
            "The existing screens were recreated with placeholder content to protect confidential company information. **Original colours, button styles, and layouts were preserved to accurately represent the initial product state.**",
            { vspace: true },
            {
                screenGallery: {
                    screens: [
                        {
                            label: "Dashboard",
                            src: "/ProjectTracker/05_existing_dashboard.png",
                            alt: "ProjectTracker existing product — Dashboard screen",
                        },
                        {
                            label: "Projects",
                            src: "/ProjectTracker/06_existing_projects.png",
                            alt: "ProjectTracker existing product — Projects screen",
                        },
                        {
                            label: "Deliverable Tracker",
                            navLines: ["Deliverable", "Tracker"],
                            src: "/ProjectTracker/07_existing_deliverable-tracker.png",
                            alt: "ProjectTracker existing product — Deliverable Tracker screen",
                        },
                        {
                            label: "Activity Tracker",
                            navLines: ["Activity", "Tracker"],
                            src: "/ProjectTracker/08_existing_activity-tracker.png",
                            alt: "ProjectTracker existing product — Activity Tracker screen",
                        },
                        {
                            label: "Gantt",
                            src: "/ProjectTracker/09_existing_gantt.png",
                            alt: "ProjectTracker existing product — Gantt screen",
                        },
                        {
                            label: "Mobilization",
                            src: "/ProjectTracker/10_existing_mobilization.png",
                            alt: "ProjectTracker existing product — Mobilization screen",
                        },
                        {
                            label: "Resources",
                            src: "/ProjectTracker/11_existing_resources.png",
                            alt: "ProjectTracker existing product — Resources screen",
                        },
                        {
                            label: "Resource Calendar",
                            src: "/ProjectTracker/12_existing_resource-calendar.png",
                            alt: "ProjectTracker existing product — Resource Calendar screen",
                        },
                    ],
                },
            },
        ],
        audit: [
            "After reviewing the existing product, I identified several UX/UI issues and accessibility concerns that needed to be addressed. I conducted a thorough audit of the product to understand the current state and identify areas for improvement.",
            { vspace: true },
            {
                imagePair: [
                    {
                        src: "/ProjectTracker/13_audit01.png",
                        alt: "ProjectTracker audit — visual consistency issue 1",
                        slotAspect: "wide",
                        fit: "cover",
                        objectPosition: "top",
                        lightbox: true,
                    },
                    {
                        src: "/ProjectTracker/14_audit02.png",
                        alt: "ProjectTracker audit — visual consistency issue 2",
                        slotAspect: "wide",
                        fit: "cover",
                        objectPosition: "top",
                        lightbox: true,
                    },
                ],
            },
            "**1. Visual Inconsistency:** The interface used inconsistent button styles, including variations in radius, size, and colour. Spacing, card styles, and visual treatments also differed across screens, making the product feel less cohesive as a system.",
            { vspace: true },
            {
                imagePair: [
                    {
                        src: "/ProjectTracker/15_audit03.png",
                        alt: "ProjectTracker audit — poor accessibility issue 1",
                        slotAspect: "wide",
                        fit: "cover",
                        objectPosition: "top",
                        lightbox: true,
                    },
                    {
                        src: "/ProjectTracker/16_audit04.png",
                        alt: "ProjectTracker audit — poor accessibility issue 2",
                        slotAspect: "wide",
                        fit: "cover",
                        objectPosition: "top",
                        lightbox: true,
                    },
                ],
            },
            "**2. Poor Accessibility:** Several colour combinations did not provide enough contrast for comfortable readability. For example, dark purple on black had a contrast ratio of 4.04, while light red on pink had a contrast ratio of 1.10. These low-contrast combinations made it harder to distinguish key information and interactive elements.",
            { vspace: true },
            {
                imagePair: [
                    {
                        src: "/ProjectTracker/17_audit05.png",
                        alt: "ProjectTracker audit — cluttered user experience issue 1",
                        slotAspect: "wide",
                        fit: "cover",
                        objectPosition: "top",
                        lightbox: true,
                    },
                    {
                        src: "/ProjectTracker/18_audit06.png",
                        alt: "ProjectTracker audit — cluttered user experience issue 2",
                        slotAspect: "wide",
                        fit: "cover",
                        objectPosition: "top",
                        lightbox: true,
                    },
                ],
            },
            "**3. Cluttered User Experience:** Some navigation paths and user flows were not intuitive. For example, as a project manager, smooth flow from Deliverable Tracker to the project's Activity Tracker should be important. But the flow from the Projects page to the Activity Tracker was unclear and tedious, which could make it harder for users to understand where to find related project activities.",
            { vspace: true },
            "Overall, the audit revealed three main areas for improvement: **creating a more consistent visual system, improving colour contrast for accessibility, and clarifying key user flows across the platform.**",
        ],
        opportunities: [
            "I found 4 main opportunities for improvement: creating a more consistent visual system, improving colour contrast for accessibility, and clarifying key user flows across the platform.",
            { vspace: true },
            "**01. Create a Cohesive Visual System**",
            {
                ul: [
                    "Standardize colours, spacing, and component styles",
                    "Establish a consistent design language across all screens",
                ],
            },
            "**02. Improve Accessibility**",
            {
                ul: [
                    "Increase colour contrast",
                    "Improve readability and visual distinction between elements",
                ],
            },
            "**03. Strengthen Information Hierarchy**",
            {
                ul: [
                    "Prioritize important information",
                    "Improve content grouping and visual scanning",
                ],
            },
            "**04. Simplify User Flows**",
            {
                ul: [
                    "Clarify navigation paths",
                    "Reduce friction between related workflows",
                ],
            },
        ],
        "design-strategy": [
            "The redesign focused on transforming the existing product into **a cohesive and scalable design system** while improving accessibility and clarifying key workflows across the platform.",
            { vspace: true },
            "**01. Establish a Design System**",
            {
                ul: [
                    "Define the use of primary and secondary colours",
                    "Standardize UI components and interaction patterns",
                    "Create a consistent spacing and layout system",
                ],
            },
            "**02. Improve Accessibility Standards**",
            {
                ul: [
                    "Apply WCAG-informed colour contrast guidelines (4.5:1 for text, 3:1 for non-text elements)",
                    "Ensure readable text and interactive elements",
                ],
            },
            "**03. Enhance Workflow Clarity**",
            {
                ul: [
                    "Simplify navigation paths",
                    "Streamline related workflows and reduce friction",
                ],
            },
        ],
        "key-improvements": [
            {
                imagePair: [
                    {
                        src: "/ProjectTracker/19_improvements01.png",
                        alt: "ProjectTracker key improvement — before",
                        caption: "Before",
                        slotAspect: "wide",
                        fit: "cover",
                        objectPosition: "top",
                        lightbox: true,
                    },
                    {
                        src: "/ProjectTracker/20_improvements02.png",
                        alt: "ProjectTracker key improvement — after",
                        caption: "After",
                        slotAspect: "wide",
                        fit: "cover",
                        objectPosition: "top",
                        lightbox: true,
                    },
                ],
            },
            "**1. Visual Consistency**",
            {
                ul: [
                    "Standardize button styles, card layouts, and visual treatments",
                    "Create a consistent spacing and layout system",
                ],
            },
            {
                imagePair: [
                    {
                        src: "/ProjectTracker/21_improvements03.png",
                        alt: "ProjectTracker key improvement — before",
                        caption: "Before",
                        slotAspect: "wide",
                        fit: "cover",
                        objectPosition: "top",
                        lightbox: true,
                    },
                    {
                        src: "/ProjectTracker/22_improvements04.png",
                        alt: "ProjectTracker key improvement — after",
                        caption: "After",
                        slotAspect: "wide",
                        fit: "cover",
                        objectPosition: "top",
                        lightbox: true,
                    },
                ],
            },
            "**2. Accessibility Improvements**",
            {
                ul: [
                    "Increase colour contrast for readability",
                    "Ensure readable text and interactive elements",
                ],
            },
            {
                imagePair: [
                    {
                        src: "/ProjectTracker/23_improvements05.png",
                        alt: "ProjectTracker key improvement — before",
                        caption: "Before",
                        slotAspect: "wide",
                        fit: "cover",
                        objectPosition: "top",
                        lightbox: true,
                    },
                    {
                        src: "/ProjectTracker/24_improvements06.png",
                        alt: "ProjectTracker key improvement — after",
                        caption: "After",
                        slotAspect: "wide",
                        fit: "cover",
                        objectPosition: "top",
                        lightbox: true,
                    },
                ],
            },
            "**3. Workflow Clarification**",
            {
                ul: [
                    "Simplify navigation paths and changed the wording of the screen for clarification",
                    "Streamline related workflows and reduce friction",
                ],
            },
            {
                imagePair: [
                    {
                        src: "/ProjectTracker/25_improvements07.png",
                        alt: "ProjectTracker key improvement — before",
                        caption: "Before",
                        slotAspect: "wide",
                        fit: "cover",
                        objectPosition: "top",
                        lightbox: true,
                    },
                    {
                        src: "/ProjectTracker/26_improvements08.png",
                        alt: "ProjectTracker key improvement — after",
                        caption: "After",
                        slotAspect: "wide",
                        fit: "cover",
                        objectPosition: "top",
                        lightbox: true,
                    },
                ],
            },
            "**4. Improved Information Hierarchy**",
            {
                ul: [
                    "Prioritize important information",
                    "Improve content grouping and visual scanning",
                ],
            },
            {
                imagePair: [
                    {
                        src: "/ProjectTracker/27_improvements09.png",
                        alt: "ProjectTracker key improvement — before",
                        caption: "Before",
                        slotAspect: "wide",
                        fit: "cover",
                        objectPosition: "top",
                        lightbox: true,
                    },
                    {
                        src: "/ProjectTracker/28_improvements10.png",
                        alt: "ProjectTracker key improvement — after",
                        caption: "After",
                        slotAspect: "wide",
                        fit: "cover",
                        objectPosition: "top",
                        lightbox: true,
                    },
                ],
            },
            "**5. Simplified User Flows**",
            {
                ul: [
                    "Clarify navigation paths",
                    "Reduce friction between related workflows",
                ],
            },
        ],
    },
    tags: ["Product Optimization", "UX/UI Redesign"],
};
